### ISSUE TITLE
Why do you set 1024 as small object threshold?

### ISSUE THREAD

**Issue by rainylt** [yukang2017/Stitcher#3]
As coco's definition, small objects are those whose area is smaller than 32*32. 
If you set 1024 as the threshold, what are the others' thresholds, like medium and large? I'm curious about it for the Figure 5 in your paper.

**Comment by yukang2017** [comment]
The threshold to distinguish medium and large objects are 96*96 = 9216. It is also defined by the coco protocal.

**Comment by rainylt** [comment]
> The threshold to distinguish medium and large objects are 96*96 = 9216. It is also defined by the coco protocal.

I see. Thanks for your kind reply.
